Fix build errors when using -Werror=unused-but-set-variable
The following errors appeared when I began building on Fedora 16. In
all cases, the variables really are never used, so they've been
removed.

drv_redhat.c: In function 'find_ifcfg_path_by_device':
drv_redhat.c:169:20: error: variable 'aug' set but not used
                            [-Werror=unused-but-set-variable]
drv_redhat.c: In function 'list_interfaces':
drv_redhat.c:315:20: error: variable 'aug' set but not used
                            [-Werror=unused-but-set-variable]
drv_redhat.c: In function 'drv_lookup_by_name':
drv_redhat.c:465:20: error: variable 'aug' set but not used
                            [-Werror=unused-but-set-variable]
drv_redhat.c: In function 'aug_put_xml':
drv_redhat.c:555:13: error: variable 'toplevel' set but not used
                            [-Werror=unused-but-set-variable]
drv_redhat.c: In function 'drv_lookup_by_mac_string':
drv_redhat.c:942:20: error: variable 'aug' set but not used
                            [-Werror=unused-but-set-variable]